[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.21"
evm_version = "paris"
via_ir = true
fs_permissions = [{ access = "read-write", path = "./out" }]

[rpc_endpoints]
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
arbitrum-sepolia = { key = "${ARBISCAN_API_KEY}" }
optimism-sepolia = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
mumbai = { key = "$POLYGONSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
